### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ikolsteren** [mkmer/whirlpool_laundry#3]
Can I get some guide on setting up?
I added the contents to custom components folder
I am using the same sensor config as the Maytag dryer integration but have changed the platform and left in just the username and password.  Config checks fine but on reboot error is:

The whirlpool_laundry platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by mkmer** [comment]
That should be indicating you have a setup in configuration.yaml - remove that and use the UI to set it up.

**Comment by ikolsteren** [comment]
Doh!   Added it now. Thought was still all in the config file. 
All setup now.  Thank you.
